services:
  crashcart:
    image: ghcr.io/gusvendegna/crashcart:latest
    container_name: crashcart
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    restart: unless-stopped
