services:
  crashcart:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crashcart
    ports:
      - "8080:8080"
    devices:
      - "/dev/video0:/dev/video0"
    environment:
      - RESOLUTION=1920x1080
      - FPS=30
    restart: unless-stopped
